version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  server-service:
    # build: ./bacachat-server
    # container_name: server-service
    image: jemtza/bacachat:server-service
    depends_on:
      - mongo
    ports:
      - 4000:4000
    restart: always
    links:
      - mongo
  client-service:
    # build: ./bacachat-client
    # container_name: client-service
    image: jemtza/bacachat:client-service
    depends_on:
      - server-service
    ports:
      - 3000:3000
    restart: always
  nginx:
    # build: .
    image: jemtza/bacachat:nginx-service
    restart: always
    ports:
      - 80:80
    depends_on:
      - server-service
      - client-service
volumes:
  mongodata:
