apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: server-service
  name: server-service
spec:
  selector:
    matchLabels:
      io.kompose.service: server-service
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: server-service
    spec:
      containers:
        - image: jemtza/bacachat:server-service
          name: server-service
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
